### ISSUE TITLE
Fiji: duplicate image

### ISSUE THREAD

**Issue by jburel** [ome/omero-insight#12]
Using duplicate image then crop is not recognized as a new image preventing the image to be imported

**Comment by jburel** [comment]
I reviewed that workflow
It works, the image is recognized as a new image and can be imported
It is probably worth adding that workflow to the training material

cc @pwalczysko

**Comment by pwalczysko** [comment]
Strangely, this workflow is working fine for me with 5.4.10 inisight-ij in full.
I think it would work with https://web-proxy.openmicroscopy.org/west-ci/job/OMERO-insight-build/lastSuccessfulBuild/artifact/build/distributions/omero-insight-imagej-5.5.0-SNAPSHOT.zip as well, except that I am being stopped during the import because of https://github.com/ome/omero-insight/issues/14#issue-431087784 - this still does not work for me.
But the image is recognized as a new image as expected even with the 5.5.x plugin.

**Comment by jburel** [comment]
It works fine. It is something we can indicate in the printout
