### ISSUE TITLE
Sanitiy checks in Import dialog

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#221]
At the moment you can enter options which cause the import to fail, e. g. invalid pixel sizes: [QA 30140](https://www.openmicroscopy.org/qa2/qa/feedback/30140/) Should have some kind of basic sanity checks there.

**Comment by pwalczysko** [comment]
I have a workflow which ends in 
``java.lang.IllegalArgumentException: values of Pixels.physicalSizeZ must be strictly positive"``

The steps to reproduce:

1. Fill in the X and Y with reasonable values (e.g. 0.1) and do not fill in Z at all 
2. Observe that import succeeds and the zutocomplete for Z is "1"
3. Fill in the X and Y with reasonable values, but also start filling in the Z. 
4. Delete the value you filled in into Z box completely.
5. The reasonable expectation now would be that the Z would be autocompleted with "1" as in Ad 2. above.
6. Instead, the autocomplete is "0.0" for the Z box, which is then failing on import with the error above.
7. I think it is fair to say that it is not about insight not checking, but rather actively suggesting a value which will later fail.

**Comment by sbesson** [comment]
Looking at this workflow, I'd also like to flag that filling out a pixel size in the way described above can lead to many issues down the lines. Incorrect metadata is usually harder to deal with than missing metadata.

I would be in favor of completing disabling the value autocompletion in this particular case.

**Comment by pwalczysko** [comment]
> Looking at this workflow, I'd also like to flag that filling out a pixel size in the way described above can lead to many issues down the lines. Incorrect metadata is usually harder to deal with than missing metadata.
> 
> I would be in favor of completing disabling the value autocompletion in this particular case.

Agree with the reasoning here, but we might be in danger of hampering usability like this.
Scenario (run through this myself as well as feedback from other users indicative to this)
User: "My images are not z-stacks, thus I do not consider z to be important. Even if it should be important, I have no idea what to fill in.  I ignore the z value and go ahead with import. But then, after a while, the import crashes (because OMERO insists on z value being filled in). I have to go back to the dialog and ponder what to fill in z (which I do not know...)."


This is a very real scenario  as documented in Tips & Tricks gif (the one I am talking about is not published yet, will pass it via email.), cc @dominikl @sbesson

**Comment by pwalczysko** [comment]
As @sbesson explained, the z value is completely optional. Thus, it would make sense to me to go for @sbesson 's original suggestion of not filling in the value if not specified at all. Nevertheless, we should test imports of such images, as the problem traspired only during the import, metadata phase.

**Comment by dominikl** [comment]
Theortically it might be possible to use `null` if the z-value is not specified and only set x and y (https://github.com/ome/omero-blitz/blob/5d27e4771af5c4c457464090edb5b450d1c11e1d/src/main/java/ome/formats/model/PixelsProcessor.java#L99-L116 thanks @sbesson ). However the `userSpecifiedPixels` field in the generated ImportSettings class (https://github.com/ome/omero-blitz/blob/5d27e4771af5c4c457464090edb5b450d1c11e1d/src/main/slice/omero/Repositories.ice#L254) is a `double[]` array, so it's not possible to pass through `null`.
