### ISSUE TITLE
OMERO.insight ImageViewer and Measurement Tool - docs

### ISSUE THREAD

**Issue by aliaksei-chareshneu** [ome/omero-insight#275]
Dear all,

Could you tell me where can I find a documentation for OMERO.insight ImageViewer and Measurement Tool? Specifically, I would be interested to learn how the ImageViewer handles the segmentation data.

https://docs.openmicroscopy.org/omero/5.6.1/users/clients-overview.html#omero-insight
This webpage provides a link to OMERO.insight user guides, however, searching "ImageViewer" term in them does not yield any results.

Best regards,
Aliaksei

**Comment by pwalczysko** [comment]
Dear Aliaksei,
Sorry for the missing item in the guides. This is caused by the fact that we do not actively add new features to OMERO.insight anymore, it rather serves as the tool for importing images into OMERO.
We have a new Image viewer, as extension of OMERO.web, see https://omero-guides.readthedocs.io/en/latest/iviewer/docs/index.html please. 
If you want to have a feel about a recommended OMERO workflow, please study the https://omero-guides.readthedocs.io/en/latest/example.html in the Getting started section. Basically, after using OMERO.insight for import, you switch to OMERO.web and do the rest there.
If you find that OMERO.iviewer is missing some features as compared with the Measurements tool of OMERO.insight, let us know, we would then answer your more detailed questions/requests here as they come.
Hope this helps
All the best
Petr 
OME Team

**Comment by aliaksei-chareshneu** [comment]
Dear Petr,

Thank you very much for a prompt response.
I am mostly interested in 3D visualization of volumetric data, e.g. segmentations. As far as I understand, OMERO.iviewer is suitable for visualization of 2D data, and it is not able to visualize volumetric data in 3D. Is OMERO.insight ImageViewer suitable for that task? 

Other than that, it seems that the only tool in OMERO suitable for that task is OMERO.FPBioimage. Is it correct?

Best regards,
Aliaksei

**Comment by pwalczysko** [comment]
Dear Aliaksei,

> As far as I understand, OMERO.iviewer is suitable for visualization of 2D data, and it is not able to visualize volumetric data in 3D. Is OMERO.insight ImageViewer suitable for that task?

Yes, OMERO.iviewer is a principally 2D viewer, this means it supporst z-stacks only by means of allowing you to view these one-by-one with a help of a horizontal slider. There is no difference in this sense between OMERO.iviewer and the OMERO.insight viewer. OMERO.insight has no advantage in this sense over OMERO.iviewer.

> the only tool in OMERO suitable for that task is OMERO.FPBioimage. Is it correct?

Yes, indeed, see https://omero-guides.readthedocs.io/en/latest/fpbioimage/docs/index.html for that please.

Thank you

All the best

Petr

**Comment by aliaksei-chareshneu** [comment]
Dear Petr,

Many thanks for the clarification and timely responses :)

Best regards,
Aliaksei
