### ISSUE TITLE
MacOS: edit or store container.xml outside the application to avoid SystemPolicyAppBundles restrictions

### ISSUE THREAD

**Issue by TK5-Tim** [ome/omero-insight#363]
Is there a way to store the container.xml for macOS outside the application to prevent any issues with [SystemPolicyAppBundles](https://macmule.com/2022/10/24/macos-ventura-and-bypassing-the-new-systempolicyappbundles-privacy-policy-control/)? 

If not that would be very helpful to prevent issues in the future otherwise it could happen that the application fails to work after changing the container.xml file. 

Thanks
Tim Keller

**Comment by dominikl** [comment]
Hi Tim,

I'm not quite sure what the problem is. If I edit something within the OMERO.insight.app, is that then supposed to trigger some kind of security error? On my OSX (12.6.5) it doesn't. 

In the OMERO.insight.cfg you can set 
```
[ArgOptions]
container.xml
```
to something else, e.g. containerImporter.xml to load the Importer UI, but you can't point it to a file outside the app package. Is it that what you meant, that this should be possible?

**Comment by TK5-Tim** [comment]
Yes, currently it is not triggering the security error, because the application is not signed. 
Because there is more and more security restrictions by Apple that could change in the future. 

For signed applications that is already the case with macOS 13.0+ 
In the future that could be also the case with unsigned applications. 

Pointing it to a file outside the app package would be helpful and one way to avoid that problem.
